version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: flash-postgres
    environment:
      POSTGRES_USER: flashuser
      POSTGRES_PASSWORD: ASDASDSA55WQ8R563DG9Y6T2QW5E5Q
      POSTGRES_DB: flashapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  flash-api:
    image: flashconect/flash-api
    container_name: flash-api
    depends_on:
      - postgres
    environment:
      PORT: 3000
      NODE_ENV: development
      LOG_LEVEL: info

      GLOBAL_API_KEY: ASDASDSA55WQ88E55R8ER5T2QW5E5Q

      ENABLE_GLOBAL_WEBHOOK: "false"
      GLOBAL_WEBHOOK_URL: https://your-webhook-url.com/webhook
      GLOBAL_WEBHOOK_SECRET: ASDASDSA55WQ8R563DG9Y6T2QW5E5Q

      ENABLE_WEBSOCKET: "false"
      GLOBAL_WEBSOCKET_SECRET: "ASDASDSA55WQ8R563DG9Y6T2QW5E5Q"

      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: flashuser
      DB_PASSWORD: ASDASDSA55WQ8R563DG9Y6T2QW5E5Q
      DB_DATABASE: flashapi
      DB_CONNECTION_LIMIT: 1000
      QUEUELIMIT: 0

      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100

      SESSION_PHONE_NAME: Flash-Api

      DELETE_TEMP_MENSAGE: "true"
      TEMP_MENSAGE: 3600

      TZ: America/Sao_Paulo

      DELETE_SESAO_DISCONECT: "true"
      TEMP_DELETE_SESSAO: 5
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres_data: